spring.application.name=BackendLibreria
spring.datasource.url=jdbc:mysql://localhost:3307/Libreria
spring.datasource.username=Admin
spring.datasource.password=Admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#spring.application.name=BackendLibreria
#
#spring.datasource.url=${DB_URI}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=${DB_DRIVER}
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect